version: "2"
services:
  # Nexus
  nexus:
    image: sonatype/docker-nexus3
    container_name: nexus
    volumes:
      - nexusdata:/nexus-data
    ports:
      - "8081:8081"
    networks:
      - jenkinsdocker_ci-net
    restart: always

volumes:
  nexusdata:

networks:
  jenkinsdocker_ci-net:
    external: true
