version: '2'
services:
  # Jenkins
  jenkins:
    build: .
    #image: jenkins:2.19.4
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkinsdata:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket in container
    restart: always

volumes:
  jenkinsdata:
