version: '2'
services:
  # Jenkins
  jenkins:
    image: jenkins:2.19.4
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkinsdata:/var/jenkins_home
    restart: always

volumes:
  jenkinsdata:
