version: '2'
services:
  # Jenkins
  jenkins:
    build: .
    image: jenkins-with-docker
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkinsdata:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket in container
    networks:
      - ci-net
    restart: always

volumes:
  jenkinsdata:

networks:
  ci-net:
    driver: bridge
